kind: pipeline
type: docker
name: Verify Code

clone:
  depth: 5

steps:
- name: Run ESLint
  image: node:14
  commands:
  - cd ./project
  - npm install
  - npm run lint:verify
  
trigger:
  event:
  - pull_request